### PR TITLE
Adding Paths, Folders to SettingType closes#1

### PR DESCRIPTION
**Pull request by GankousKhan**

### CODE REVIEW

**Comment by HavenDV** [comment]
Good)) But it also means support for forms for these types

**Comment by HavenDV** [comment]
image
For example: these are the MoviesRunner settings. You need to create one field that takes several values: like the PATH environment variable in Windows10

**Comment by christopher-lamb** [comment]
Ah alright. Will work on adding that as soon as I resolve a few dependency issues preventing me from building. Felt like it was too simple of a request. Thanks for the clarification.

**Comment by HavenDV** [comment]
The program is my personal development, so it would be interesting to know about these issues. Create a separate Issue for them, please.

**Comment by christopher-lamb** [comment]
Sure no problem. It is just a single nuget package missing for SharpShell, but having some permission issues on writing to the registry that I would like to read through first before I run with privileges. I can create a case for the nuget package if you would like for formality.

**Comment by HavenDV** [comment]
I also fixed one dependency problem in the last commit. I should have done it before

**Comment by HavenDV** [comment]
Regarding SharpShell - [here](https://github.com/dwmkerr/sharpshell/pull/163) you can get additional information. I fixed the problem of the existing version and use my version of the library

**Comment by HavenDV** [comment]
This library itself is needed to create this panel:image

**Comment by christopher-lamb** [comment]
That merge was accidental. Forgot I had some commands aliased for work while trying to rebase with upstream locally. If I need to revert any changes from that let me know. Need to switch to my other git client.

**Comment by HavenDV** [comment]
https://github.com/HavenDV/HomeCenter.NET/wiki/Adding-a-new-module-to-the-program

**Comment by HavenDV** [comment]
https://github.com/HavenDV/HomeCenter.NET/issues/1

**Pull request closed without merging**
